---
- name: Install nginx
  become: yes
  yum: name=nginx state=present

- name: Start nginx
  become: yes
  service: name=nginx state=started enabled=yes

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  become: yes
