---
- name: Upgrade all packages
  become: yes
  yum:
    name: '*'
    state: latest
- name: Set timezone to Asia/Tokyo
  become: yes
  timezone:
    name: Asia/Tokyo
- name: Restart crond to apply new timezone
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: crond
